### ISSUE TITLE
Wrong Dimension

### ISSUE THREAD

**Issue by TehZombiJesus** [Nan1t/NanoLimbo#17]
Hey there,

I just starting using this and it works great except for the dimension.

No matter what I put in the settings file, I always get this. ![image](https://user-images.githubusercontent.com/81379135/151381156-ddd082be-aece-4d26-9957-4417648eabdc.png)

Dimension is currently set for "THE_END" but it seems to always show "OVERWORLD"

**Comment by Nan1t** [comment]
I can't reproduse this. For me and for other users it works. Which client you use, mods, etc. I need any useful info.

**Comment by TehZombiJesus** [comment]
I'm using the Pterodactyl Egg ---> [here](https://github.com/parkervcp/eggs/tree/master/game_eggs/minecraft/java/nanolimbo)
Latest Waterfall as my proxy
Default Minecraft client.

**Comment by Nan1t** [comment]
Never heard about this. Have you tried to start limbo directly, just as java program?

**Comment by TehZombiJesus** [comment]
No but I can certainly try that. Give me a few minutes :)

**Comment by TehZombiJesus** [comment]
I found the issue. My beautiful shader pack :(

**Comment by Nan1t** [comment]
Don't worry, it's okay :)
