### ISSUE TITLE
WARNING Undefined incoming packet: 0x15

### ISSUE THREAD

**Issue by PixelDev0** [Nan1t/NanoLimbo#2]
Hello,

When a player connects to the limbo server, the console gets spammed with the following lines (not in order):
`
11.02 08:06:16 [Server] WARNING Undefined incoming packet: 0x12
11.02 08:06:16 [Server] WARNING Undefined incoming packet: 0x15
`

Any help would be appreciated. Thanks.

**Comment by Nan1t** [comment]
Please, read instruction before asking questions. To disable these messge, set `debugLevel` to `0` in the config.

**Comment by PixelDev0** [comment]
The debug level has been set to 0 however.
