### ISSUE TITLE
1.18.2 support 

### ISSUE THREAD

**Issue by mastermc05** [Nan1t/NanoLimbo#25]
![image](https://user-images.githubusercontent.com/63639746/158888559-9597e73b-358e-4a24-8fb5-db4ddb427da5.png)

**Comment by mastermc05** [comment]
waiting for https://github.com/Nan1t/NanoLimbo/pull/22 to be official <3

**Comment by Nan1t** [comment]
Hello, @mastermc05. Yes, i merged it. Check the new limbo version in Releases section.
