### ISSUE TITLE
"Unsupported class file major version 62" when building on latest Java

### ISSUE THREAD

**Issue by BBaoVanC** [Nan1t/NanoLimbo#26]
I get this error when trying to build using Java 18 or 17. I had to use Java 8 to be able to build it. Could this be set in the Gradle settings somehow so it automatically uses a compatible Java version?

**Comment by Nan1t** [comment]
I seen some commit from @BoomEaro for this. Last version compiles with JDK 17.0.2 for me.

**Comment by BBaoVanC** [comment]
> I seen some commit from @BoomEaro for this. Last version compiles with JDK 17.0.2 for me.

It looks like that their pull request changes the Gradle settings to output a JAR for Java 8, but now it looks like the problem is that Gradle wrapper itself was outdated.

See #31, where I updated the Gradle wrapper which seems to fix this.
