### ISSUE TITLE
1.19 Client can't join the Limbo Server

### ISSUE THREAD

**Issue by RaphiMC** [Nan1t/NanoLimbo#32]
When joining with vanilla 1.19 the "Downloading Terrain" screen never closes and the player has to restart the game

**Comment by Nan1t** [comment]
Set y field in spawnPosition bore than 255. By default it's 400.

**Comment by RaphiMC** [comment]
Does not work, its seems like the config breaks itself after starting the Limbo server. I am using the latest github release.

What I configure:
![image](https://user-images.githubusercontent.com/50594595/177305813-b7bd50a7-bc8e-4d98-bbe3-6437e42981a6.png)
What it looks like after starting the Limbo server:
![image](https://user-images.githubusercontent.com/50594595/177305879-ba006431-7e71-498c-ac1a-9e6149dbba95.png)
