### ISSUE TITLE
1.9.1 Can't join the Limbo server

### ISSUE THREAD

**Issue by RaphiMC** [Nan1t/NanoLimbo#33]
When joining with 1.9.1 a packet decoding error occurs

Client error:
![image](https://user-images.githubusercontent.com/50594595/177318557-72a6cc0d-9e44-4303-9266-981240197fc4.png)

Bungeecord error:
![image](https://user-images.githubusercontent.com/50594595/177318766-ce5ec0cc-18f2-41ed-b170-ddbed81ac82d.png)

**Comment by Nan1t** [comment]
Fixed in 1.4.1

**Comment by RaphiMC** [comment]
Can confirm, it is fixed
