### ISSUE TITLE
Loading terrain indefinetly until kick/restart

### ISSUE THREAD

**Issue by Benjiiben53** [Nan1t/NanoLimbo#39]
Hello, i have a problem with NanoLimbo, when i am connecting to it, it's says **Loading terrain...** indefinitely :/

I am on **1.18.2 Vanilla**,
**NanoLimbo** is behind the **latest WaterFall** Proxy with **ViaVersion**.

The version of NanoLimbo is the 1.4.1 and the bug appear also on 1.4.0. I didn't tried a another one.
The console with debug Level of 2 print this:

```
[INFO]: Starting server...
[INFO]: Server started on localhost/127.0.0.1:25563
[INFO]: Player Benjiiben53 connected (/192.168.1.150:45695) [V1_18_2]
```

I also tried to touch the netty options:
> Tried turn true and false the useEpoll.
> Didn't touch the threads options.

If you need more information i am here ;)

**Comment by Nan1t** [comment]
Check your spawn height in config. It must be more than 256

**Comment by nyu19** [comment]
> Hello, i have a problem with NanoLimbo, when i am connecting to it, it's says **Loading terrain...** indefinitely :/
> 
> I am on **1.18.2 Vanilla**, **NanoLimbo** is behind the **latest WaterFall** Proxy with **ViaVersion**.
> 
> The version of NanoLimbo is the 1.4.1 and the bug appear also on 1.4.0. I didn't tried a another one. The console with debug Level of 2 print this:
> 
> ```
> [INFO]: Starting server...
> [INFO]: Server started on localhost/127.0.0.1:25563
> [INFO]: Player Benjiiben53 connected (/192.168.1.150:45695) [V1_18_2]
> ```
> 
> I also tried to touch the netty options:
> 
> > Tried turn true and false the useEpoll.
> > Didn't touch the threads options.
> 
> If you need more information i am here ;)

Are You using Pterodactyl? If yes, This thing happened to me aswell!! I did some tweaking and it kinda works for me now. Let me know if u want the Jar file I am using.

**Comment by Anime-Forevere** [comment]
> > Hello, i have a problem with NanoLimbo, when i am connecting to it, it's says **Loading terrain...** indefinitely :/
> > I am on **1.18.2 Vanilla**, **NanoLimbo** is behind the **latest WaterFall** Proxy with **ViaVersion**.
> > The version of NanoLimbo is the 1.4.1 and the bug appear also on 1.4.0. I didn't tried a another one. The console with debug Level of 2 print this:
> > ```
> > [INFO]: Starting server...
> > [INFO]: Server started on localhost/127.0.0.1:25563
> > [INFO]: Player Benjiiben53 connected (/192.168.1.150:45695) [V1_18_2]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I also tried to touch the netty options:
> > > Tried turn true and false the useEpoll.
> > > Didn't touch the threads options.
> > 
> > 
> > If you need more information i am here ;)
> 
> Are You using Pterodactyl? If yes, This thing happened to me aswell!! I did some tweaking and it kinda works for me now. Let me know if u want the Jar file I am using.

Hey, can you provide it so people know the solution of it.

**Comment by nyu19** [comment]
@Anime-Forevere With respect to #32, It does seem that Pterodactyl is having some issue with nanolimbo. Especially when it comes to `y level` it somehow changes the `y` to `"true"` due to which there is no way anyone can change the `y level` from config. 
( Trust Me I tried everything 😶 ) so the only option left for me was to _hard code_ the `y level`. The only difference in the provided jar file is the `y` level is hardcoded. (again thanks to @Nan1t for making this project open source!)

[NanoLimbo-y300-nyu.zip](https://github.com/Nan1t/NanoLimbo/files/9313583/NanoLimbo-y300-nyu.zip)

**Comment by Benjiiben53** [comment]
Hello, i'm back !

So first _i'm not using pterodactyl_, i'm on _Debain 11_ and i'm using _java 17_ from [https://adoptium.net/](url)

**In the settings the spawn position was set to Y64, i tried to set it to 400 like in the #32 and it works !**

Wierd bug but thats working now !

Thanks all for the Help !

**Comment by AliceDTRH** [comment]
Workaround for those using pterodactyl: use "y" instead of y
