### ISSUE TITLE
Stuck on "Loading Terrain"

### ISSUE THREAD

**Issue by CommandCracker8** [Nan1t/NanoLimbo#43]
Hello. I am using NanoLimbo with Bungeecord and running it through Pterodactyl panel, and when I try to connect to it I just get stuck on the "Loading Terrain" screen:
![image](https://user-images.githubusercontent.com/68102222/189884906-4f09c0b1-0248-4ef3-9dba-5200da6736c8.png)
Any help would be appreciated!

**Comment by U61vashka** [comment]
Probably you are using 1.18+.

And this is occurs when player spawns on lower coordinates than max_y and chunks not loaded.

Solution for this: Spawn player on y 257 or load all chunks (harder to do).
![изображение](https://user-images.githubusercontent.com/85439143/189890766-4f7bca48-d2f2-4551-913d-d84860288653.png)
![изображение](https://user-images.githubusercontent.com/85439143/189890786-86a9d825-c98d-443b-9182-64fa08533caa.png)

But this is only theory. And i am not the developer of NanoLimbo

**Comment by CommandCracker8** [comment]
It turns out it was a problem with [Pterodactyl panel](https://pterodactyl.io/), thanks for replying so quickly though!
