### ISSUE TITLE
"Plugin must have a plugin.yml or bungee.yml"

### ISSUE THREAD

**Issue by MrRagtime** [Nan1t/NanoLimbo#48]
> ### **I'm using [v1.4.1](https://github.com/Nan1t/NanoLimbo/releases/tag/v1.4.1)**
> [22:53:32 WARN]: Could not load plugin from file plugins/NanoLimbo-1.4.1-all.jar
> java.lang.NullPointerException: Plugin must have a plugin.yml or bungee.yml
>         at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:82114a5:507]
>         at net.md_5.bungee.api.plugin.PluginManager.detectPlugins(PluginManager.java:434) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:82114a5:507]
>         at net.md_5.bungee.BungeeCord.start(BungeeCord.java:285) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:82114a5:507]
>         at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:82114a5:507]
>         at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:82114a5:507]
>
> ## - **[Log file](https://github.com/Nan1t/NanoLimbo/files/10049026/latest.log)**

**Comment by Nan1t** [comment]
This is not a plugin. Read installation instruction
