### ISSUE TITLE
QUESTION: Will this be updated to the 1.17 protocol?

### ISSUE THREAD

**Issue by Tydium** [Nan1t/NanoLimbo#5]
I'm asking because I kinda dislike using viaversion...

**Comment by Nan1t** [comment]
This always works with viaversions on proxy side. You think this won't work after 1.17 release?

**Comment by Nan1t** [comment]
Added in v1.3

**Comment by Tydium** [comment]
oh man, Ive been using via version and nearly forgot that the issue existed. Thanks!
