### ISSUE TITLE
[Feature] Adding a /version or /ver Command

### ISSUE THREAD

**Issue by Finoway** [Nan1t/NanoLimbo#69]
Hello, I assist some servers that use NanoLimbo, and I find it unfortunate that there is no command or other way to check the version of NanoLimbo. It would be helpful to have a command like "/version" or "/ver" that displays the version, similar to Bukkit/Spigot/Paper/BungeeCord...

**Comment by Nan1t** [comment]
Added in 1.6 but for console only.
