### ISSUE TITLE
[Feature] Packet Rate Limit

### ISSUE THREAD

**Issue by Potothingi** [Nan1t/NanoLimbo#70]
I think something like Paper's packet rate limit will be needed to mitigate network attacks against limbo.

**Comment by Nan1t** [comment]
Check it out in the new version. But this feature is not completely tested yet.

**Comment by Nan1t** [comment]
> packetSize: 1024' is too small
You can increase it as you wish. And can you provide example of valid income packet that potentially will be more than 1024 bytes?

> Isn't the count reset if packets come in more than once per second?
Yes, this implementation counts data per sec. If next packed received after that period we're starting from zero. If you want to increase this period, I can move it to settings.
