### ISSUE TITLE
Log to file

### ISSUE THREAD

**Issue by vaio2005** [Nan1t/NanoLimbo#80]
I use this limbo server to redirect players to use the correct port number. I often fall victim to port scanning/bot spam, so I sometimes like to go and manually ban from the firewall offending IP addresses, if I see that they are from a hosting service or from a VPN.
Having NanoLimbo log to a file, and ideally having the option to choose what to log, would be great for this.

Thanks for making this piece of software.

**Comment by Nan1t** [comment]
Check the latest release, there is what you asked. Without option to choose what to log, but might be useful anyway.

**Comment by vaio2005** [comment]
Thanks a lot! It appears to be working as expected. 
Having full logs is fine, so thank you!
