### ISSUE TITLE
Cant seem to get Waterfall to connect to it

### ISSUE THREAD

**Issue by TomLewis** [Nan1t/NanoLimbo#9]
Set as default server in waterfall, wont connect, just bypasses and goes to my survival.

**Comment by Nan1t** [comment]
Check IP forwarding settings on proxy and limbo side. I tested this on Waterfall and it works for me.

**Comment by TomLewis** [comment]
I got it working in the end, I had to fully stop my Waterfall and then start it again, not just reboot it!
